### PR TITLE
update: New rules for the penalty area

### PR DESCRIPTION
**Pull request by mrshu**
### Please describe your change in one or two sentences

* Give more priority to the goalie inside the penalty area

* Ensure that breaking the goalie's priority inside the penalty area is
  costly by moving the ball to the furthest unoccupied neutral spot.

### Please explain why do you think this change should be in the rules

* Minimize the amount of "sumo"-like gameplay that happens at RCJ Soccer.

### CODE REVIEW

**Comment by mrshu** [comment]
See what the rules would look like in [the last draft](https://robocupjuniortc.github.io/soccer-rules/mrshu/penalty-area/rules.html)!

**Comment by mrshu** [comment]
See what the rules would look like in [the last draft](https://robocupjuniortc.github.io/soccer-rules/mrshu/penalty-area/rules.html)!

**Comment by mrshu** [comment]
See what the rules would look like in [the last draft](https://robocupjuniortc.github.io/soccer-rules/mrshu/penalty-area/rules.html)!

**Comment by mrshu** [comment]
See what the rules would look like in [the last draft](https://robocupjuniortc.github.io/soccer-rules/mrshu/penalty-area/rules.html)!

**Comment by mrshu** [comment]
See what the rules would look like in [the last draft](https://robocupjuniortc.github.io/soccer-rules/mrshu/penalty-area/rules.html)!

**Comment by pavelpetrovic** [comment]
I have some problems with the penalty area concept. It definitely needs more explanation in the rules text.

It is stated in the rules that robots are considered to be in the penalty area (PA) only when they are completely in. But how about the rule 1.8. Inside the PA? This is not clear. Is it the point of touch that determines if the rule applies even when the attacking robot is almost completely outside of the PA?
That would make it very difficult for the attacking robot: it did not even have a chance to detect entering the PA using its sensors, yet, very strict rules already apply - basically if it is not allowed to push the ball in the PA, it has to kick it from outside.
IF the "completely in" applies to all 3 elements (both robots + ball) of the rule 1.8, then this rule helps only in the rare case of two robots being parallel each to other in front of the goal and the attacker still being very aggressive. Yes, it is a good rule then, but it appears to be too weak.

**Comment by pavelpetrovic** [comment]
Everything suggests that the rule 1.8. Inside the PA applies only when both robots are completely in the area, but it needs to be reiterated and stated clearly, otherwise it leads to confusion.
If so, then this rule seems to be weak: pushing the goalie is still OK until the robot is completely in - which is the final stage 1cm before the goal is scored (30 - (22+7) = 1).

**Comment by mrshu** [comment]
Thanks for catching this @pavelpetrovic -- the last part of the 1.8 rule was a redundant leftover from previous versions of the rules, with very little effect on the current ones. It will be removed in #54.

In general, the reasoning behind these new rules for the penalty area can be summarized in this sentence which is part of the new draft:

> While inside this area, attacking robots are not supposed to touch the goalie nor the ball in any way.

The idea is to restrict the sumo-like gameplay as much as possible. The attacking robots would be given some leeway as the black line is not part of the penalty area (and can therefore be detected) but in general the new draft would prevent robots from just "driving the ball" to the opponents goal, as that has been identified as one of the primary sources of this sumo-like gameplay we are trying to avoid.

Looking at your comment above, would you find this kind of a rule too strict? It is still just a draft and can (and most probably will) change, so I would be very interested in hearing your opinion.

Thanks agian!

**Pull request merged**
