### PR TITLE
Add omnidirectional mirror restriction

### PR DESCRIPTION
**Pull request by aquahika**
### Please describe your change in one or two sentences

Omnidirectional lenses must be designed and manfactured by students.

### Please explain why do you think this change should be in the rules

Some of the team designed an omnidirectional lens by themselves but delegated manufacturing to professional metal processing and polishing companies.  The prices in various but around hundreds of euros or dollars. It’s still not “commercial”, but also not made by students.

My idea is we argue that the omnidirectional lens must be designed and produced including polishing by students and prohibit outsourcing production to other companies or adults.

### CODE REVIEW

**Comment by dbscoach** [comment]
I see some issues with this proposal:

- Definition Question: What qualifies an omnidirectional lens?
- Manufacturing lenses is almost impossible for students. Very few teams successfully made mirrors which are significantly easier to accomplish than lenses. We would only make teams move to more cameras with narrower lenses or COTS omnidirectional mirrors.
- We do not restrict the sourcing of any non-optical components, how would this restriction improve the learning or robotics aspects of RCJ soccer?
- Enforcement: Neither local, regional, superregional nor the international tournament were strict about the mirror rules while they were in force. We would likely create an environment that advantages strongly the teams that bend the rules most again.

**Comment by mrshu** [comment]
cc @aquahika @Adman @MikeRCJ @javier687  @marcodankel

**Comment by aquahika** [comment]
Oh, I mean mirror. not lens

**Comment by dbscoach** [comment]
Oh, I see. Do we think there is a serious advantage to be gained by means of expensive mirrors if cheap cameras + fisheye lenses allow having reasonable resolution for much cheaper?

**Comment by JavadRah** [comment]
I think we must change our perspective.
It does not mean that we force the students to polish the mirror themselves.
Everyone relies on a part of the robot according to their requirements, some of them have good electronics, another team for accurate shooting, Another team works on the communication between their two robots, and a team on their mirror.  Normally, the student cannot reach all these matters with the limited time he has and only focuses on one or two parts.
This is the feature of RoboCup Junior that allows creativity to grow.  Putting extra rules will only kill creativity.  
We do not want to force students in the direction we want.  We must respect their freedom of action.

**Comment by dbscoach** [comment]
@JavadRah Consider this: The current draft of the rules (see https://junior.forum.robocup.org/t/2023-draft-rules-public-discussion-soccer-rules-2023/2616) contains language permitting multiple cameras, fisheye lenses and any kind of bough optical components. We know for a fact that very good but very expensive ready-made mirrors exist. The question is now wether these will give teams that are able to buy them an unfair advantage over teams that use the new freedoms in vision system components but with less available money. If that is the case we would want to prohibit using these expensive mirrors by way of the changes introduced in this PR. What do you think? Will expensive mirrors be used and will they be so effective as to be an unfair advantage over teams that have only cheaper cameras and fisheye lenses?

**Comment by mrshu** [comment]
Thank you all for the discussion here. This change did not make it to the rules in the end but we'll try our best to revisit it in the future.

Thanks!

**Pull request closed without merging**
